from draw_solution import draw_solution
from pent_solver import solve
from assembly_jewels_matrixgen import create_moves_matrix
import pprint

# Solves the assembly of the planners puzzle using a matrix that is
# autogenerated

output_file = "assembly_of_planners_solution.svg"

full_matrix = create_moves_matrix()

all_solutions = solve(full_matrix)

# just in case drawing totally fails
data_printer = pprint.PrettyPrinter(indent=4)
data = data_printer.pformat(all_solutions)

with open("emergency_solution_export.json", 'w') as file:
    file.write(data)

draw_solution(all_solutions, output_file)
